name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup GraalVM environment
      uses: DeLaGuardo/setup-graalvm@2.0
    - name: Build with Maven
      run: mvn -B package --file pom.xml
